# Generated by Django 5.1.4 on 2025-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
